### ISSUE TITLE
exec /manager: exec format error   

### ISSUE THREAD

**Issue by midzelis** [Skarlso/crd-bootstrap#113]
When deploying, I'm getting the following error:

```
exec /manager: exec format error      
```

from the pod: crd-bootstrap/crd-bootstrap-controller-manager

Running this on an `aarch64` platform (Oracle free-tier VMs)

**Comment by Skarlso** [comment]
Thank you for reporting! I'll create some multi-arch images. :)

**Comment by Skarlso** [comment]
@midzelis Do you know the architecture that it's running on? Is it `arm64`?

**Comment by Skarlso** [comment]
Is it darwin?

**Comment by midzelis** [comment]
Using https://en.wikipedia.org/wiki/Oracle_Linux - I don't know too much about it, but it seems to use a RHEL linux kernel. 

It uses Arm-based Ampere A1 VMs. uname returns 'aarch64' as the architecture....

```
Linux argocd-server-f865679d9-gd5p5 5.15.0-206.153.7.el8uek.aarch64 #2 SMP Thu May 9 16:18:54 PDT 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by midzelis** [comment]
Oh, and thanks!

**Comment by Skarlso** [comment]
Okay cool. That's hat I thought. I'm adding arm to the mix. Goreleaser is just messing with me for whatever reason. 🤣

**Comment by Skarlso** [comment]
@midzelis Would you mind trying now please? v0.9.8.
