### ISSUE TITLE
Improve chart.yaml for better visibility at artifacthub

### ISSUE THREAD

**Issue by eshepelyuk** [Skarlso/crd-bootstrap#35]
Hello

Currenly the page is looking quite empty

1. no proper description
2. no README
3. no links to src repo
4. no crd examples
5. no tags\labels

it all can be improved via Char.yaml, as an exampel one could use this helm chart.

https://artifacthub.io/packages/helm/apicurio-registry-helm/apicurio-registry

**Comment by Skarlso** [comment]
Thanks for the sample! I was looking for a nice example. :)

**Comment by Skarlso** [comment]
@eshepelyuk hm, I can't claim ownership of the helm repo. It's grayed out. I think the artifact file is in the right location though, so I'm not sure what to do about that.

**Comment by ievgenii-shepeliuk** [comment]
1. Have you followed [THIS GUIDE](https://artifacthub.io/docs/topics/repositories/helm-charts/) ?
2. you can contact devs for support here https://cloud-native.slack.com/archives/C0103CTR3RB

**Comment by Skarlso** [comment]
Of course I have. Because I read all the documentation every time when I'm trying to do something new. How even dare you suggest, that I completely skipped this part? 🤦 😆 😆

**Comment by ievgenii-shepeliuk** [comment]
From here 
https://github.com/Skarlso/crd-bootstrap/pkgs/container/helm%2Fcrd-bootstrap/versions?filters%5Bversion_type%5D=tagged

i clealy see you had not followed the guide.

**Comment by Skarlso** [comment]
Sorry, the previous sentence was sarcasm / attempted joke. I did miss this step.
